server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

app:
  baseurl: http://auth-server:9000
logging:
  level:
    org:
      springframework:
        security: trace
              