server:
  port: 9000

spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            scope:
              - user:email
              - read:user
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

app:
  baseurl: http://auth-server:9000
  default:
    scopes: openid,email,profile,phone,address
  client:
    clientIdPrefix: vapps
  security:
    publicKey: ${VAPPS_AUTH_SERVER_PUBLIC_KEY}
    privateKey: ${VAPPS_AUTH_SERVER_PRIVATE_KEY}
logging:
  level:
    org:
      springframework:
        security: trace
              