spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: authorization-server
  main:
    allow-circular-references: true
  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTHORIZATION_SERVER_BASE_URL}
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            redirect-uri: ${GITHUB_REDIRECT_URI}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

app:
  baseurl: ${AUTHORIZATION_SERVER_BASE_URL}
  default:
    scopes: openid
  client:
    clientIdPrefix: vapps
logging:
  level:
    org:
      springframework:
        security: trace
              